agent_count: 1
run_id: parsing_grokking_ppo_fork_B_exp5
log_path: /data/mchivuku/embodiedai/iclr/grokking/small/ppo/${run_id}
mode: train
train_eps: 1000
hydra.job.chdir: True
cuda: 0
experiment: parsing

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
